name: Approvals notification

on:
  pull_request_review:
    types: [submitted]

jobs:
  send_matrix_approved_msg:
    if: contains(github.event.pull_request.body, 'Project Abstract')
    runs-on: ubuntu-latest
    steps:
      - run: echo 'APPROVALS=?' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 1**')
        run: echo 'APPROVALS=2' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 2**')
        run: echo 'APPROVALS=3' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 3**')
        run: echo 'APPROVALS=5' >> $GITHUB_ENV
      - run: echo "YEA"