name: Approvals notification

on:
  pull_request_review:
    types: [submitted]

jobs:
  send_matrix_approved_msg:
    if: github.event.review.state == 'commented' && contains(github.event.pull_request.body, 'Project Abstract')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'APPROVALS=?' >> $GITHUB_ENV
          echo 'MSG="APPROVED"' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 1**')
        run: echo 'APPROVALS=2' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 2**')
        run: echo 'APPROVALS=3' >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, '[x] **Level 3**')
        run: echo 'APPROVALS=5' >> $GITHUB_ENV
      - run: echo 'COMMENTS=14' >> $GITHUB_ENV
      - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
      - if: ${{ steps.reviews.outputs.commented == env.COMMENTS && !(github.event.pull_request.state == "merged") }}
        run: echo 'MSG="READY TO MERGE"' >> $GITHUB_ENV
      - uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: 'matrix.web3.foundation'
          token: ${{ secrets.MATRIX_TOKEN }}
          channel: ${{ secrets.MATRIX_CHANNEL_ID }}
          message: |
            [TEST] ${{ env.MSG }}: [${{ github.event.pull_request.title }}](https://github.com/w3f/Grants-Program/pull/${{ github.event.pull_request.number }}) has been approved by ${{ github.event.review.user.login }}. 
            Approvals: ${{ steps.reviews.outputs.commented }}/${{ env.COMMENTS }}