name: Stale checker

#on:
#  schedule:
#    - cron: "30 10 * * *"

# on:
#   push:
#     branches:
#       - 'placeholder/**'

on:
  pull_request:
    types: [opened]

jobs:
  mark_as_stale:
    # if:  github.repository_owner == 'w3f'
    runs-on: ubuntu-latest
    steps:
    - run: npm install axios
    - id: stale
      uses: 0xCaso/label-stale-pull-requests@v1
      with:
        context: ${{ toJSON(github) }}
        token: ${{ secrets.GITHUB_TOKEN }}
        stale-timeout: -1
    - if: steps.stale.outputs.message != ''
      # run: echo "The message was ${{ steps.stale.outputs.message }}"
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.web3.foundation'
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: ${{ secrets.MATRIX_CHANNEL_ID }}
        message: |
          ${{ steps.stale.outputs.message }}
