name: Test markdown

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
      name: build
      if: github.event.pull_request.merged
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ steps.comment-branch.outputs.head_ref }}
        - uses: actions/setup-node@v2
          with:
            node-version: "16.16.0"
        - name: yarn build
          run: |
            git config --global user.email "grants-deployer@users.noreply.github.com"
            git config --global user.name "grants-deployer"
            echo "machine github.com login grants-deployer password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
            yarn && yarn build
        - name: send success message on matrix channel
          if: ${{ success() }}
          id: matrix-chat-message-failure
          uses: fadenb/matrix-chat-message@v0.0.6
          with:
            homeserver: 'matrix.web3.foundation'
            token: ${{ secrets.MATRIX_TOKEN }}
            channel: ${{ secrets.MATRIX_CHANNEL_ID }}
            message: |
              ${{ github.ref }}
